config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  resources :coaches do
    resources :coach_comments
  end

  resources :students do
    resources :student_comments
    resources :educational_qualifications
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
        has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
        # Validate content type
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	# Validate filename
	validates_attachment_file_name :avatar, matches: [/png\z/, /jpe?g\z/]
        has_many :coach_comments, dependent: :destroy
	validates :first_name, presence: true,
                    length: { minimum: 3 }
	validates :last_name, presence: true,
                    length: { minimum: 3 }
	validates :dob, presence: true,
                    length: { minimum: 6 }
	validates :subject_or_topics, presence: true
	validates :address, presence: true
end

app/models/coach_comment.rb
class CoachComment < ApplicationRecord
  belongs_to :coach
end

app/models/educational_qualification.rb
class EducationalQualification < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user, foreign_key: "user_id", class_name: "User"
        has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
        # Validate content type
        validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
        # Validate filename
        validates_attachment_file_name :avatar, matches: [/png\z/, /jpe?g\z/]
        has_many :student_comments, dependent: :destroy
	has_many :educational_qualifications, :through => :user
        validates :first_name, presence: true,
                    length: { minimum: 3 }
        validates :last_name, presence: true,
                    length: { minimum: 3 }
        validates :dob, presence: true,
                    length: { minimum: 6 }
        validates :interests, presence: true
        validates :address, presence: true
end

app/models/student_comment.rb
class StudentComment < ApplicationRecord
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
	has_one :student, foreign_key: "email", class_name: "Student"
	has_many :educational_qualifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coach_comments_controller.rb
class CoachCommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @coach = Coach.find(params[:coach_id])
    @coach_comment = @coach.coach_comments.create(coach_comment_params)
    redirect_to coach_path(@coach)
  end

  def destroy
    @coach = Coach.find(params[:coach_id])
    @coach_comment = @coach.coach_comments.find(params[:id])
    @coach_comment.destroy
    redirect_to coach_path(@coach)
  end
 
  private
    def coach_comment_params
      params.require(:coach_comment).permit(:commenter, :title, :body)
    end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def index
    @coachs = Coach.all
  end

  def new
    @coach = Coach.new
  end

  def edit
    @coach = Coach.find(params[:id])
  end

  def create
    @coach = Coach.new(coach_params)
 
    if @coach.save
      redirect_to @coach
    else 
      render 'new'
    end
    #render plain: params[:coach].inspect
  end

  def update
    @coach = Coach.find(params[:id])
 
    if @coach.update(coach_params)
      redirect_to @coach
    else
      render 'edit'
    end
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy
	 
    redirect_to coaches_path
  end

  def show
    @coach = Coach.find(params[:id])
  end

private
  def coach_params
    params.require(:coach).permit(:user_id, :first_name, :last_name, :dob, :subject_or_topics, :address, :avatar)
  end
end

app/controllers/educational_qualifications_controller.rb
class EducationalQualificationsController < ApplicationController
  def create
    @student = Student.find(params[:student_id])
    @params = qualification_params
    @params[:uuid] = SecureRandom.uuid
    @params[:user_id] = @student.user_id
    @qualification = @student.user.educational_qualifications.create(@params)
    redirect_to article_path(@student)
  end
 
  private
    def qualification_params
      params.require(:educational_qualification).permit(:qualification_name, :institute_name, :enrolled_years, :graduation_date, :description, :major, :parent_body, :location, :result, :remarks)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @coaches = Coach.all
    @students = Student.all
  end
end

app/controllers/student_comments_controller.rb
class StudentCommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @student = Student.find(params[:student_id])
    @student_comment = @student.student_comments.create(student_comment_params)
    redirect_to student_path(@student)
  end

  def destroy
    @student = Student.find(params[:student_id])
    @student_comment = @student.student_comments.find(params[:id])
    @student_comment.destroy
    redirect_to student_path(@student)
  end

  private
    def student_comment_params
      params.require(:student_comment).permit(:commenter, :title, :body)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to studentes_path
  end

  def show
    @student = Student.find(params[:id])
  end

private
  def student_params
    params.require(:student).permit(:user_id, :first_name, :last_name, :dob, :interests, :address, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coach_comments_helper.rb
module CoachCommentsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/educational_qualifications_helper.rb
module EducationalQualificationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_comments_helper.rb
module StudentCommentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/coach_comments/_coach_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= coach_comment.commenter %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= coach_comment.title %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= coach_comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [coach_comment.coach, coach_comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>

app/views/coach_comments/_form.html.erb
<%= form_with(model: [ @coach, @coach.coach_comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/coaches/_form.html.erb
<%= form_with(model: @coach, local: true) do |form| %>
 <% if @coach.errors.any? %>
  <div id="error_explanation">
      <h2>
        <%= pluralize(@coach.errors.count, "error") %> prohibited
        this coach from being saved:
      </h2>
      <ul>
        <% @coach.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :subject_or_topics %><br>
    <%= form.text_field :subject_or_topics %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/coaches/edit.html.erb
<h1>Edit Coach Information</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<h1>Listing all registerd coaches</h1>

<%= link_to 'New coach', new_coach_path %>
<%= link_to 'Home Page', home_index_path %>
 
<table>
  <tr>
    <th>User ID</th>
    <th>Name</th>
    <th>Date of birth</th>
    <th>Subject or topics</th>
    <th>Address</th>
    <th colspan="3"></th>
  </tr>
 
  <% @coachs.each do |coach| %>
    <tr>
      <td><%= coach.user_id %></td>
      <td><%= coach.first_name %> <%= coach.last_name %></td>
      <td><%= coach.dob %></td>
      <td><%= coach.subject_or_topics %></td>
      <td><%= coach.address %></td>
      <td><%= link_to 'Show', coach_path(coach) %></td>
      <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
      <td><%= link_to 'Destroy', coach_path(coach),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p>
  <strong>User ID:</strong>
  <%= @coach.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coach.first_name %> <%= @coach.last_name %>
</p>
 
<p>
  <strong>Date of birth:</strong>
  <%= @coach.dob %>
</p>

<p>
  <strong>Subject or topics:</strong>
  <%= @coach.subject_or_topics %>
</p>

<p>
  <strong>Address:</strong>
  <%= @coach.address %>
</p>

<%= image_tag @coach.avatar.url(:medium) %>

<h2>Comments For this coach</h2>
<%= render @coach.coach_comments %>

<h2>Add a comment:</h2>
<%= render 'coach_comments/form' %>

<%= week_calendar number_of_weeks: 2 do |date| %>
  <%= date %>
<% end %>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>

app/views/home/index.html.erb
<style type="text/css">
.container {
   max-width: 960px;
}

.row {
  display: flex;
  flex-wrap: wrap;
}

.card {
  position: relative;
  display: flex;
  min-width: 0;
}

.card-body {
  width: 250px;
  display: block;
  flex: 1 1 auto;
}
.card-image {
  width: 160px;
  height: 220px;
  float: left;
  clear: right;
}
.card-image img {
  width: 160px;
  height: 220px;
  vertical-align: middle;
  border-style: none;
}

.card-text {
  display: block;
  margin-top: 225px;
}

.MuiPaper-elevation2-14 {
    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 3px 1px -2px rgba(0, 0, 0, 0.12);
}

.MuiPaper-rounded-11 {
    border-radius: 4px;
}
.MuiPaper-root-10 {
    background-color: #fff;
}
</style>
<h1>Online Coaching Management Systems</h1>

<%= link_to 'List of coaches', controller: 'coaches' %>
<%= link_to 'List of students', controller: 'students' %>

<h3>Suggested coaches</h3>

  <div class="container">
  <div class="row">
  <% @coaches.each do |coach| %>
    <div class="card MuiPaper-elevation2-1 MuiPaper-rounded-11 MuiPaper-root-10">
      <div class="card-body">
      <div class="card-image"><%= image_tag coach.avatar.url(:medium) %></div>
      <div class="card-text"><%= link_to [coach.first_name, coach.last_name].join(' '), coach_path(coach) %></div>
      </div>
    </div>
  <% end %>
  </div>
  </div>

<h3>Suggested Students</h3>
<div class="container">
  <div class="row">
  <% @students.each do |student| %>
    <div class="card">
      <div class="card-body">
      <div class="card-image"><%= image_tag student.avatar.url(:medium) %></div>
      <div class="card-text"><%= link_to [student.first_name, student.last_name].join(' '), student_path(student) %></div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/student_comments/_form.html.erb
<%= form_with(model: [ @student, @student.student_comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_area :title %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/student_comments/_student_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= student_comment.commenter %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= student_comment.title %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= student_comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [student_comment.student, student_comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>

app/views/students/_form.html.erb
<%= form_with(model: @student, local: true) do |form| %>
 <% if @student.errors.any? %>
  <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :user_id %><br>
    <%= form.text_field :user_id %>
  </p>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :dob %><br>
    <%= form.text_field :dob %>
  </p>

  <p>
    <%= form.label :interests %><br>
    <%= form.text_field :interests %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
  <%= image_tag @student.avatar.url(:medium) %>
  </p>
  <p>
  <%= form.file_field :avatar %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student Information</h1>

<%= render 'form' %>

<h2>Add a qualification:</h2>
<%= form_with(model: [ @student, @student.educational_qualifications.build ], local: true) do |form| %>
  <p>
    <%= form.label :qualification_name %><br>
    <%= form.text_field :qualification_name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :institute_name %><br>
    <%= form.text_field :institute_name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing all registerd studentes</h1>

<%= link_to 'New student', new_student_path %>
<%= link_to 'Home Page', home_index_path %>
 
<table>
  <tr>
    <th>User ID</th>
    <th>Name</th>
    <th>Date of birth</th>
    <th>Intersts</th>
    <th>Address</th>
    <th colspan="3"></th>
  </tr>
 
  <% @students.each do |student| %>
    <tr>
      <td><%= student.user_id %></td>
      <td><%= student.first_name %> <%= student.last_name %></td>
      <td><%= student.dob %></td>
      <td><%= student.interests %></td>
      <td><%= student.address %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Destroy', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>User Id:</strong>
  <%= @student.user_id %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @student.first_name %> <%= @student.last_name %>
</p>
 
<p>
  <strong>Date of birth:</strong>
  <%= @student.dob %>
</p>
 
<p>
  <strong>Interests:</strong>
  <%= @student.interests %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <%= image_tag @student.avatar.url(:medium) %>
</p>

<h2>Education Qualification</h2>
<% @student.educational_qualifications.each do |qual| %>
  <p>
    <strong>Qualification name:</strong>
    <%= qual.qualification_name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= qual.description %>
  </p>
  <p>
    <strong>Major:</strong>
    <%= qual.major %>
  </p>
  <p>
    <strong>Institute name:</strong>
    <%= qual.institute_name %>
  </p>
  <p>
    <strong>Location:</strong>
    <%= qual.location %>
  </p>
  <p>
    <strong>Enrolled years:</strong>
    <%= qual.enrolled_years %>
  </p>
  <p>
    <strong>Graduation date:</strong>
    <%= qual.graduation_date %>
  </p>
  <p>
    <strong>Parent body:</strong>
    <%= qual.parent_body %>
  </p>
  <p>
    <strong>Result:</strong>
    <%= qual.result %>
  </p>
  <p>
    <strong>Remarks:</strong>
    <%= qual.remarks %>
  </p>
<% end %>

<h2>Comments For this student</h2>
<%= render @student.student_comments %>

<h2>Add a comment:</h2>
<%= render 'student_comments/form' %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>